import { title } from "process";

const posts = [
  {
    id: 1,
    slug: "post-1",
    year: "1998",
    publisher: "Robert Friedrich",
    printed_country: "China",
    illustrator: "Gwynedd M. Hudson",
    ISBN: "0 90778 572 7",
    price: "6",
    purchased: "Used Bookstore",
    condition: "Good",
  },
  {
    id: 2,
    slug: "post-2",
    year: "1986",
    publisher: "Chancellor Press",
    printed_country: "Portugal",
    illustrator: "Arthur Rackham",
    ISBN: "0 907486 79 7",
    price: "6",
    purchased: "Used Bookstore",
    condition: "Good",
  },
  {
    id: 3,
    slug: "post-3",
    year: "1991",
    publisher: "Unicorn Publishing House",
    printed_country: "Unknown",
    illustrator: "Greg Hildebrandt",
    ISBN: "Unknown",
    price: "1.99",
    purchased: "Value Village",
    condition: "Good",
  },
  {
    id: 4,
    slug: "post-4",
    year: "1990",
    publisher: "Dell Yearling",
    printed_country: "Unknown",
    illustrator: "Unknown",
    ISBN: "0 71009 01400",
    price: "4.99",
    purchased: "Value Village",
    condition: "Good",
  },
  {
    id: 5,
    slug: "post-5",
    year: "1994",
    publisher: "Bracken Books",
    printed_country: "Singapore",
    illustrator: "John Tenniel",
    ISBN: "1 85170 109 5",
    price: "4.99",
    purchased: "Value Village",
    condition: "Good",
  },
  {
    id: 6,
    slug: "post-6",
    year: "1990",
    publisher: "Troll Associates",
    printed_country: "Unknown",
    illustrator: "Katheryn A. Couri",
    ISBN: "0 8167 1862 8",
    price: "4.99",
    purchased: "Value Village",
    condition: "Good",
  },
];

export default posts;
